# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_transfer_pb2 as file__transfer__pb2


class FileServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FileDownload = channel.unary_stream(
                '/FileServer/FileDownload',
                request_serializer=file__transfer__pb2.FileDownloadReq.SerializeToString,
                response_deserializer=file__transfer__pb2.FileDownloadRsp.FromString,
                )
        self.GetFileList = channel.unary_stream(
                '/FileServer/GetFileList',
                request_serializer=file__transfer__pb2.GetListReq.SerializeToString,
                response_deserializer=file__transfer__pb2.GetListRsp.FromString,
                )
        self.FileUpload = channel.stream_unary(
                '/FileServer/FileUpload',
                request_serializer=file__transfer__pb2.FileUploadReq.SerializeToString,
                response_deserializer=file__transfer__pb2.FileUploadRsp.FromString,
                )


class FileServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FileDownload(self, request, context):
        """Downloading file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileList(self, request, context):
        """Get list files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileUpload(self, request_iterator, context):
        """Uploading file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FileDownload': grpc.unary_stream_rpc_method_handler(
                    servicer.FileDownload,
                    request_deserializer=file__transfer__pb2.FileDownloadReq.FromString,
                    response_serializer=file__transfer__pb2.FileDownloadRsp.SerializeToString,
            ),
            'GetFileList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFileList,
                    request_deserializer=file__transfer__pb2.GetListReq.FromString,
                    response_serializer=file__transfer__pb2.GetListRsp.SerializeToString,
            ),
            'FileUpload': grpc.stream_unary_rpc_method_handler(
                    servicer.FileUpload,
                    request_deserializer=file__transfer__pb2.FileUploadReq.FromString,
                    response_serializer=file__transfer__pb2.FileUploadRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FileDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileServer/FileDownload',
            file__transfer__pb2.FileDownloadReq.SerializeToString,
            file__transfer__pb2.FileDownloadRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileServer/GetFileList',
            file__transfer__pb2.GetListReq.SerializeToString,
            file__transfer__pb2.GetListRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileUpload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FileServer/FileUpload',
            file__transfer__pb2.FileUploadReq.SerializeToString,
            file__transfer__pb2.FileUploadRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
