# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_transfer.proto\"\x1f\n\x0f\x46ileDownloadReq\x12\x0c\n\x04name\x18\x01 \x01(\t\";\n\x0f\x46ileDownloadRsp\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x03\"\x0c\n\nGetListReq\"(\n\nGetListRsp\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\"9\n\rFileUploadReq\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x03\"\x1f\n\rFileUploadRsp\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa3\x01\n\nFileServer\x12\x36\n\x0c\x46ileDownload\x12\x10.FileDownloadReq\x1a\x10.FileDownloadRsp\"\x00\x30\x01\x12+\n\x0bGetFileList\x12\x0b.GetListReq\x1a\x0b.GetListRsp\"\x00\x30\x01\x12\x30\n\nFileUpload\x12\x0e.FileUploadReq\x1a\x0e.FileUploadRsp\"\x00(\x01\x62\x06proto3')



_FILEDOWNLOADREQ = DESCRIPTOR.message_types_by_name['FileDownloadReq']
_FILEDOWNLOADRSP = DESCRIPTOR.message_types_by_name['FileDownloadRsp']
_GETLISTREQ = DESCRIPTOR.message_types_by_name['GetListReq']
_GETLISTRSP = DESCRIPTOR.message_types_by_name['GetListRsp']
_FILEUPLOADREQ = DESCRIPTOR.message_types_by_name['FileUploadReq']
_FILEUPLOADRSP = DESCRIPTOR.message_types_by_name['FileUploadRsp']
FileDownloadReq = _reflection.GeneratedProtocolMessageType('FileDownloadReq', (_message.Message,), {
  'DESCRIPTOR' : _FILEDOWNLOADREQ,
  '__module__' : 'file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:FileDownloadReq)
  })
_sym_db.RegisterMessage(FileDownloadReq)

FileDownloadRsp = _reflection.GeneratedProtocolMessageType('FileDownloadRsp', (_message.Message,), {
  'DESCRIPTOR' : _FILEDOWNLOADRSP,
  '__module__' : 'file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:FileDownloadRsp)
  })
_sym_db.RegisterMessage(FileDownloadRsp)

GetListReq = _reflection.GeneratedProtocolMessageType('GetListReq', (_message.Message,), {
  'DESCRIPTOR' : _GETLISTREQ,
  '__module__' : 'file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:GetListReq)
  })
_sym_db.RegisterMessage(GetListReq)

GetListRsp = _reflection.GeneratedProtocolMessageType('GetListRsp', (_message.Message,), {
  'DESCRIPTOR' : _GETLISTRSP,
  '__module__' : 'file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:GetListRsp)
  })
_sym_db.RegisterMessage(GetListRsp)

FileUploadReq = _reflection.GeneratedProtocolMessageType('FileUploadReq', (_message.Message,), {
  'DESCRIPTOR' : _FILEUPLOADREQ,
  '__module__' : 'file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:FileUploadReq)
  })
_sym_db.RegisterMessage(FileUploadReq)

FileUploadRsp = _reflection.GeneratedProtocolMessageType('FileUploadRsp', (_message.Message,), {
  'DESCRIPTOR' : _FILEUPLOADRSP,
  '__module__' : 'file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:FileUploadRsp)
  })
_sym_db.RegisterMessage(FileUploadRsp)

_FILESERVER = DESCRIPTOR.services_by_name['FileServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEDOWNLOADREQ._serialized_start=23
  _FILEDOWNLOADREQ._serialized_end=54
  _FILEDOWNLOADRSP._serialized_start=56
  _FILEDOWNLOADRSP._serialized_end=115
  _GETLISTREQ._serialized_start=117
  _GETLISTREQ._serialized_end=129
  _GETLISTRSP._serialized_start=131
  _GETLISTRSP._serialized_end=171
  _FILEUPLOADREQ._serialized_start=173
  _FILEUPLOADREQ._serialized_end=230
  _FILEUPLOADRSP._serialized_start=232
  _FILEUPLOADRSP._serialized_end=263
  _FILESERVER._serialized_start=266
  _FILESERVER._serialized_end=429
# @@protoc_insertion_point(module_scope)
